Assignment_2
Shaposhnikov-Alexey/python_basic_programming pull request #1
Opened 2020-03-15 20:14 UTC by Shaposhnikov-Alexey

Petty database for checking last tv shows

2020-03-16 18:07 UTC, SpirinEgor requested changes
Не надо хранить саму бд в репо, она и так при запуске инициализируется

2020-03-16 18:07 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +"""
""" -- способ задания строк, а не комментирование.
Если эта функция не нужна -- удали.

2020-03-16 18:07 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +            subs += f'<a href=\"{url}' + sub.find("a").get("href")[1:] + "\">" + sub.text + "</a><br>"
Довольно странное сочетание, ты же можешь через `f-''` всю строку создавать, зачем по кускам и конкатенировать?

2020-03-16 18:07 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +        cursor.execute("SELECT * FROM TVShows")
Выглядит, как костыль на проверку наличия информации в бд.
Лучше всегда вызывать `parse`, но делать `INSERT or REPLACE`, чтобы данные не дублировались.

2020-03-16 23:51 UTC, Shaposhnikov-Alexey commented on assignment_2/server/app_db.py
> +        cursor.execute("SELECT * FROM TVShows")
@SpirinEgor внес правки по замечаниям

2020-03-24 18:13 UTC, SpirinEgor requested changes

2020-03-24 18:13 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +        parse_fanserials()
Парсинг лучше вынести из инициализации и вызывать после. Вот простой пример, сейчас сайт этот недоступен, поэтому инициализация повисла и ждёт таймаута, приложение не запускается и клиенту некуда отправлять запросы.

2020-03-24 18:13 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +        parse_fanserials()
Ну и db.commit лучше вернуть тогда

2020-03-24 18:13 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +        db.commit()
Коммит лучше делать один, то есть в цикле делаешь `cursor.execute`, а затем, после цикла, `commit`

2020-03-24 18:13 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +    url = 'http://fanserials.auction/'
Недоступен :)

2020-03-25 16:03 UTC, Shaposhnikov-Alexey commented on assignment_2/server/app_db.py
> +    url = 'http://fanserials.auction/'
@SpirinEgor по замечаниям исправил, а сайт у меня доступен ¯\_(ツ)_/¯

2020-03-30 08:35 UTC, SpirinEgor requested changes
По коду замечаний нет.
Но в пр прилетело куча ненужных файлов из других заданий + снова появился файл базы данных.

2020-04-01 14:13 UTC, closed without merging