Task_03
Shaposhnikov-Alexey/python_basic_programming pull request #6
Opened 2020-04-19 14:07 UTC by Shaposhnikov-Alexey

2020-04-20 10:23 UTC, SpirinEgor requested changes

2020-04-20 10:23 UTC, SpirinEgor commented on hw3/face_swap.py
> +    return True
```
x_inside rect[0] <= point[0] <= rect[0] + rect[2]
y_inside rect[1] <= points[1] <= rect[1] + rect[3]
return x_inside and y_inside
```

2020-04-20 10:23 UTC, SpirinEgor commented on hw3/face_swap.py
> +        pt3 = (t[4], t[5])
```
pt1, pt2, pt3 = [(t[i], t[i + 1]) for i in [0, 2, 4]]
pt += [pt1, pt2, pt3]
```

2020-04-20 10:23 UTC, SpirinEgor commented on hw3/face_swap.py
> +        pt3 = (t[4], t[5])
Наверное можно ещё аккуратнее сделать, если подумать немного. Но так хотя бы глаз не дёргается :)

2020-04-20 11:59 UTC, Shaposhnikov-Alexey commented on hw3/face_swap.py
> +        pt3 = (t[4], t[5])
Спасибо, поправил

2020-04-27 09:23 UTC, SpirinEgor approved these changes

2020-04-27 10:39 UTC, merged